SYMBOLS = {
    "Atlas": "اطلس",
    "Foolad": "فولاد",
    "Khodro": "خودرو",
    "Shasta": "شستا",
    "Vbmelat": "وبملت",
    "Fars": "فارس",
    "Zob": "ذوب",
    "Kegel": "کگل",
    "Shabdar": "شبندر",
    "Vasandogh": "وصندوق",
    "Simorgh": "سیمرغ",
    "Faofogh": "فافق",
    "Farda": "وفردا",
    "Vapasar": "وپاسار",
    "Hegmatan": "سهگمت",
    "Sabagher": "سباقر",
    "Dezagros": "دزاگرس",
    "Shomal": "وشمال",
    "Kazeron": "کازرو",
    "Vanovin": "ونوین",
    "Shahr": "وشهر",
    "Mohtasham": "محتشم",
    "Khabahman": "خبهمن",
    "Ghegel": "غگل",
    "Asanpardakht": "آپ",
    "Pakhsh": "پخش",
    "Dalbar": "دالبر",
    "Sepaha": "سپاها",
    "Sekhazar": "سخزر",
    "Khemotor": "خموتور",
    "Taira": "تایرا",
    "Alomina": "آلومینا",
    "Saman": "سامان",
    "Ghamino": "غمینو",
    "Shenaft": "شنفت",
    "Torail": "توریل",
    "Paak": "غپاک",
    "Pekavir": "پکویر",
    "Faravar": "فرآور",
    "Ghakorosh": "غکورش",
    "Vasepehr": "وسپهر",
    "Khagostar": "خگستر",
    "Simin": "سیمین",
    "Nahal": "نهال",
    "Ayar": "عیار",
    "Sinergy": "سینرژی",
    "Salam": "سلام",
    "Vatosa": "وتوصا",
    "Vabahman": "وبهمن",
    "Khabahman": "خبهمن",
    "Khodran": "خودران",
    "Kelid": "کلید",
    "Darono": "دارونو",
    "Farmani": "فارمانی",
    "Sorenafood": "سورنافود",
    "Faraalgorithm": "فرا الگوریتم",
    "Tameshk": "تمشک",
    "Doax": "دوایکس",
    "Kahroba": "کهربا",
    "Khobregan": "خبرگان",
    "Hybrid": "هیبرید",
    "Lotus": "لوتوس",
    "Tamelat": "تملت",
    "Darayekom": "دارا یکم",
    "Palayesh": "پالایش",
    "Karis": "کاریس",
    "Mokhtalet": "مختلط",
    "Ahrom": "اهرم",
    "Afran": "افران",
    "Tala": "طلا",
    "Kashane": "کاشانه",
    "Maze": "مزه",
    "Laziz": "لذیذ",
    "Servatam": "ثروتم"
}

SYMBOL_NAMES = list(SYMBOLS.keys())

MACRO_SYMBOLS = {
    "USD_IRR": {"source": "yfinance", "ticker": "USDIRR=X", "name": "USD/IRR"},
    "Gold_USD": {"source": "yfinance", "ticker": "GC=F", "name": "Gold/USD"},
    "Silver_USD": {"source": "yfinance", "ticker": "SI=F", "name": "Silver/USD"},
    "Oil_USD": {"source": "yfinance", "ticker": "CL=F", "name": "Oil/USD"},
    "TSE_Index": {"source": "pytse_client", "ticker": "شاخص كل", "name": "Tehran Stock Exchange Index"},
    "BTC_USD": {"source": "yfinance", "ticker": "BTC-USD", "name": "BTC/USD"},
}

